// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameActionExecution = "action_executions"

// ActionExecution mapped from table <action_executions>
type ActionExecution struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AgentID        string    `gorm:"column:agent_id;not null" json:"agent_id"`
	IdempotencyKey string    `gorm:"column:idempotency_key;not null" json:"idempotency_key"`
	IntentType     string    `gorm:"column:intent_type;not null" json:"intent_type"`
	Dt             int32     `gorm:"column:dt;not null" json:"dt"`
	ResultCode     string    `gorm:"column:result_code;not null" json:"result_code"`
	UpdatedState   []uint8   `gorm:"column:updated_state" json:"updated_state"`
	Events         []uint8   `gorm:"column:events" json:"events"`
	AppliedAt      time.Time `gorm:"column:applied_at;not null" json:"applied_at"`
	CreatedAt      time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName ActionExecution's table name
func (*ActionExecution) TableName() string {
	return TableNameActionExecution
}
