// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentState = "agent_states"

// AgentState mapped from table <agent_states>
type AgentState struct {
	AgentID           string     `gorm:"column:agent_id;primaryKey" json:"agent_id"`
	Hp                int32      `gorm:"column:hp;not null" json:"hp"`
	Hunger            int32      `gorm:"column:hunger;not null" json:"hunger"`
	Energy            int32      `gorm:"column:energy;not null" json:"energy"`
	X                 int32      `gorm:"column:x;not null" json:"x"`
	Y                 int32      `gorm:"column:y;not null" json:"y"`
	Version           int64      `gorm:"column:version;not null" json:"version"`
	UpdatedAt         time.Time  `gorm:"column:updated_at" json:"updated_at"`
	Inventory         string     `gorm:"column:inventory" json:"inventory"`
	Dead              bool       `gorm:"column:dead;not null" json:"dead"`
	DeathCause        string     `gorm:"column:death_cause" json:"death_cause"`
	OngoingActionType string     `gorm:"column:ongoing_action_type" json:"ongoing_action_type"`
	OngoingActionEnd  *time.Time `gorm:"column:ongoing_action_end_at" json:"ongoing_action_end_at"`
	OngoingActionMins int32      `gorm:"column:ongoing_action_minutes" json:"ongoing_action_minutes"`
}

// TableName AgentState's table name
func (*AgentState) TableName() string {
	return TableNameAgentState
}
