// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameAgentResourceNode = "agent_resource_nodes"

// AgentResourceNode mapped from table <agent_resource_nodes>
type AgentResourceNode struct {
	ID            int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AgentID       string    `gorm:"column:agent_id;not null" json:"agent_id"`
	TargetID      string    `gorm:"column:target_id;not null" json:"target_id"`
	ResourceType  string    `gorm:"column:resource_type;not null" json:"resource_type"`
	X             int32     `gorm:"column:x;not null" json:"x"`
	Y             int32     `gorm:"column:y;not null" json:"y"`
	DepletedUntil time.Time `gorm:"column:depleted_until;not null" json:"depleted_until"`
	CreatedAt     time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt     time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName AgentResourceNode's table name
func (*AgentResourceNode) TableName() string {
	return TableNameAgentResourceNode
}
