// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentCredential = "agent_credentials"

// AgentCredential mapped from table <agent_credentials>
type AgentCredential struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AgentID   string    `gorm:"column:agent_id;not null" json:"agent_id"`
	KeySalt   []uint8   `gorm:"column:key_salt;not null" json:"key_salt"`
	KeyHash   []uint8   `gorm:"column:key_hash;not null" json:"key_hash"`
	Status    string    `gorm:"column:status;not null;default:active" json:"status"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName AgentCredential's table name
func (*AgentCredential) TableName() string {
	return TableNameAgentCredential
}
