// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameAgentSession = "agent_sessions"

// AgentSession mapped from table <agent_sessions>
type AgentSession struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	SessionID  string    `gorm:"column:session_id;not null" json:"session_id"`
	AgentID    string    `gorm:"column:agent_id;not null" json:"agent_id"`
	StartTick  int64     `gorm:"column:start_tick;not null" json:"start_tick"`
	Status     string    `gorm:"column:status;not null" json:"status"`
	DeathCause string    `gorm:"column:death_cause" json:"death_cause"`
	EndedAt    time.Time `gorm:"column:ended_at" json:"ended_at"`
	CreatedAt  time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
}

// TableName AgentSession's table name
func (*AgentSession) TableName() string {
	return TableNameAgentSession
}
