// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameDomainEvent = "domain_events"

// DomainEvent mapped from table <domain_events>
type DomainEvent struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	AgentID    string    `gorm:"column:agent_id" json:"agent_id"`
	Type       string    `gorm:"column:type;not null" json:"type"`
	OccurredAt time.Time `gorm:"column:occurred_at;not null" json:"occurred_at"`
	Payload    []uint8   `gorm:"column:payload" json:"payload"`
	CreatedAt  time.Time `gorm:"column:created_at;default:now()" json:"created_at"`
}

// TableName DomainEvent's table name
func (*DomainEvent) TableName() string {
	return TableNameDomainEvent
}
