// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWorldClockState = "world_clock_state"

// WorldClockState mapped from table <world_clock_state>
type WorldClockState struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	StateKey   string    `gorm:"column:state_key;not null" json:"state_key"`
	Phase      string    `gorm:"column:phase;not null" json:"phase"`
	SwitchedAt time.Time `gorm:"column:switched_at;not null" json:"switched_at"`
	UpdatedAt  time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName WorldClockState's table name
func (*WorldClockState) TableName() string {
	return TableNameWorldClockState
}
