// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameWorldChunk = "world_chunks"

// WorldChunk mapped from table <world_chunks>
type WorldChunk struct {
	ID        int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	ChunkX    int32     `gorm:"column:chunk_x;not null" json:"chunk_x"`
	ChunkY    int32     `gorm:"column:chunk_y;not null" json:"chunk_y"`
	Phase     string    `gorm:"column:phase;not null" json:"phase"`
	Tiles     []uint8   `gorm:"column:tiles;not null" json:"tiles"`
	UpdatedAt time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
}

// TableName WorldChunk's table name
func (*WorldChunk) TableName() string {
	return TableNameWorldChunk
}
