ALTER TABLE agent_states
  ADD COLUMN IF NOT EXISTS inventory_capacity INTEGER NOT NULL DEFAULT 30,
  ADD COLUMN IF NOT EXISTS inventory_used INTEGER NOT NULL DEFAULT 0;

ALTER TABLE world_objects
  ADD COLUMN IF NOT EXISTS object_type TEXT,
  ADD COLUMN IF NOT EXISTS quality TEXT,
  ADD COLUMN IF NOT EXISTS capacity_slots INTEGER,
  ADD COLUMN IF NOT EXISTS used_slots INTEGER,
  ADD COLUMN IF NOT EXISTS object_state TEXT;
